/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserSchema"];
                };
            };
            responses: {
                /** @description The user was successfully created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            _id: string;
                            name: string;
                            email: string;
                            token: string;
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Some server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log-in to the system */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description User email */
                        email: string;
                        /** @description User password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Log-in Successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            _id: string;
                            name: string;
                            email: string;
                            token: string;
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Some server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log out user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return information about current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["UserResponse"];
                        };
                    };
                };
                /** @description Not authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Some server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all bookings
         * @description Retrieve bookings based on user role:
         *     - Admin users can view all bookings
         *     - Member users can only view their own bookings
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of bookings retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            count: number;
                            data: components["schemas"]["PopulatedBooking"][];
                        };
                    };
                };
                /** @description Not authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Create a new booking
         * @description Create a new booth booking for an exhibition (member only)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description ID of the exhibition to book */
                        exhibition: string;
                        /**
                         * @description Type of booth (small/big)
                         * @enum {string}
                         */
                        boothType: "small" | "big";
                        /** @description Number of booths to book (total booths per user per exhibition must not exceed 6) */
                        amount: number;
                    };
                };
            };
            responses: {
                /** @description Order created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            data: components["schemas"]["PopulatedBooking"];
                        };
                    };
                };
                /** @description Invalid request - Total booths per exhibition must not exceed 6 or quota exceeded */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authorized - Member access required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Exhibition not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/booking/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a booking by ID
         * @description admin can view any booking, member can only view their own
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the booking to view */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the booking details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            data: components["schemas"]["PopulatedBooking"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Booking not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Update booking
         * @description admin can update any booking, member can only update their own
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the booking to update */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Type of booth (small/big)
                         * @enum {string}
                         */
                        boothType: "small" | "big";
                        /** @description Number of booths (total booths per exhibition must not exceed 6) */
                        amount: number;
                    };
                };
            };
            responses: {
                /** @description Booking updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            data: components["schemas"]["PopulatedBooking"];
                        };
                    };
                };
                /** @description Validation error or booth quota exceeded */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Booking not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Delete booking
         * @description admin can delete any booking, member can only delete their own
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the booking to delete */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Booking not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exhibitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all exhibitions
         * @description Retrieve all available exhibitions with populated bookings. Accessible by all users.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of exhibitions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            count?: number;
                            data?: components["schemas"]["PopulatedExhibitionResponse"][];
                        };
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Create a new exhibition
         * @description Create a new exhibition. Only accessible by admin users. Start date must not be earlier than current date.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateExhibitionRequest"];
                };
            };
            responses: {
                /** @description Exhibition created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["ExhibitionResponse"];
                        };
                    };
                };
                /** @description Invalid input or start date is in the past */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Admin access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exhibitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an exhibition by ID
         * @description Retrieve details of a specific exhibition with populated bookings. Accessible by all users.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Exhibition ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Exhibition details retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["PopulatedExhibitionResponse"];
                        };
                    };
                };
                /** @description Exhibition not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Update an exhibition
         * @description Update an existing exhibition. Only accessible by admin users.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Exhibition ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateExhibitionRequest"];
                };
            };
            responses: {
                /** @description Exhibition updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["ExhibitionResponse"];
                        };
                    };
                };
                /** @description Invalid input or start date is in the past */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Admin access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Exhibition not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Delete an exhibition
         * @description Delete an exhibition. Only accessible by admin users.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Exhibition ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Exhibition deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                        };
                    };
                };
                /** @description Not authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Admin access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Exhibition not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUserSchema: {
            /** @description Name of user */
            name: string;
            /** @description Email of user */
            email: string;
            /** @description Telephone number of user */
            tel: string;
            /**
             * @description Role of user (member or admin), default is member
             * @enum {string}
             */
            role?: "member" | "admin";
            /** @description Password of user */
            password: string;
            /**
             * Format: date
             * @description Date of creation (default is current date-time)
             * @example 2023-08-20
             */
            createdAt?: string;
        };
        UserResponse: {
            /** @description Name of user */
            name: string;
            /** @description Email of user */
            email: string;
            /** @description Telephone number of user */
            tel: string;
            /**
             * @description Role of user (member or admin), default is member
             * @enum {string}
             */
            role: "member" | "admin";
            /**
             * Format: date
             * @description Date of creation (default is current date-time)
             * @example 2023-08-20
             */
            createdAt: string;
        };
        BookingResponse: {
            /** @description Auto-generated MongoDB ObjectId */
            readonly _id: string;
            /** @description Reference to the user who made the booking */
            readonly user: {
                _id: string;
                name: string;
                email: string;
            };
            /**
             * @description Type of booth (small/big)
             * @enum {string}
             */
            boothType: "small" | "big";
            /** @description Number of booths booked (total booths per exhibition must not exceed 6) */
            amount: number;
            /**
             * Format: date-time
             * @description Auto-generated timestamp of creation
             */
            readonly createdAt: string;
            /**
             * Format: date-time
             * @description Auto-generated timestamp of last update
             */
            readonly updatedAt: string;
        };
        PopulatedBooking: components["schemas"]["BookingResponse"] & {
            /** @description Reference to the exhibition being booked */
            exhibition: {
                _id: string;
                name: string;
                description: string;
                venue: string;
                /** Format: date-time */
                startDate: string;
                durationDay: number;
                smallBoothQuota: number;
                bigBoothQuota: number;
            };
        };
        CreateExhibitionRequest: {
            /** @description Name of the exhibition */
            name: string;
            /** @description Detailed description of the exhibition */
            description: string;
            /** @description Location where the exhibition will be held */
            venue: string;
            /**
             * Format: date
             * @description Start date of the exhibition (cannot be earlier than current date)
             */
            startDate: string;
            /** @description Duration of exhibition in days */
            durationDay: number;
            /** @description Number of small booths available */
            smallBoothQuota: number;
            /** @description Number of big booths available */
            bigBoothQuota: number;
            /** @description URL of the exhibition poster picture */
            posterPicture: string;
        };
        UpdateExhibitionRequest: {
            /** @description Name of the exhibition */
            name?: string;
            /** @description Detailed description of the exhibition */
            description?: string;
            /** @description Location where the exhibition will be held */
            venue?: string;
            /**
             * Format: date
             * @description Start date of the exhibition (cannot be earlier than current date)
             */
            startDate?: string;
            /** @description Duration of exhibition in days */
            durationDay?: number;
            /** @description Number of small booths available */
            smallBoothQuota?: number;
            /** @description Number of big booths available */
            bigBoothQuota?: number;
            /** @description URL of the exhibition poster picture */
            posterPicture?: string;
        };
        ExhibitionResponse: {
            /** @description Auto-generated MongoDB ObjectId */
            readonly _id: string;
            /** @description Name of the exhibition */
            name: string;
            /** @description Detailed description of the exhibition */
            description: string;
            /** @description Location where the exhibition will be held */
            venue: string;
            /**
             * Format: date
             * @description Start date of the exhibition
             */
            startDate: string;
            /** @description Duration of exhibition in days */
            durationDay: number;
            /** @description Number of small booths available */
            smallBoothQuota: number;
            /** @description Number of big booths available */
            bigBoothQuota: number;
            /** @description URL of the exhibition poster picture */
            posterPicture: string;
            /**
             * Format: date-time
             * @description Auto-generated timestamp of creation
             */
            readonly createdAt: string;
            /**
             * Format: date-time
             * @description Auto-generated timestamp of last update
             */
            readonly updatedAt: string;
        };
        PopulatedExhibitionResponse: components["schemas"]["ExhibitionResponse"] & {
            /** @description List of bookings associated with this exhibition */
            bookings: components["schemas"]["BookingResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
